name: Publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: publish
        uses: actions/git-pages@v2
        with:
          site: https://blog.ensko.at/
          server: grebedoc.dev
          password: ${{ secrets.SITE_PASSWORD }}
          source: dist/
