name: Publish
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        uses: https://github.com/withastro/action@v5

      - name: publish
        uses: actions/git-pages@v2
        with:
          site: https://blog.ensko.at/
          server: grebedoc.dev
          password: ${{ secrets.SITE_PASSWORD }}
          source: dist/
